@(
    # Core
    'Read-ConfigFile'
    'RegexPatterns'
    'Format-Template'
    'Test-Condition'
    'Wait-Condition'
    'Write-ConfigFile'
    'Reset-Module'
    'New-Shortcut'
    'Get-ACGCoreRegexPattern'
    'Get-ACGCoreRegexPatternNames'
    'Test-ACGCoreRegexPattern'
    # SecureStrings
    'Unlock-SecureString'
    'ConvertTo-CertificateSecuredString'
    'ConvertFrom-CertificateSecuredString'
    'Import-SecureString'
    'Export-SecureString'
    # Credentials
    'Restore-PSCredential'
    'New-PSCredential'
    'Save-PSCredential'
    'ConvertFrom-PSCredential'
    'ConvertTo-PSCredential'
    # OS
    'Add-LogonOp'
    'Get-RegValue'
    'Remove-LogonOp'
    'Set-ProcessPrivilege'
    'Set-RegValue'
    'Set-RegKeyOwner'
    'Set-WinAutoLogon'
    #Strings
    'ConvertTo-Base64String'
    'ConvertTo-UnicodeEscapedString'
    'ConvertFrom-Base64String'
    'ConvertFrom-UnicodeEscapedString'
    'New-RandomString'
)